// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type ClaimedPerk struct {
	ID         int32
	EmployeeID sql.NullInt32
	PerkID     sql.NullInt32
	CreatedAt  sql.NullTime
}

type EcoRouteLog struct {
	ID                    int32
	EmployeeID            sql.NullInt32
	TransportMode         string
	DistanceKm            string
	Co2SavedKg            string
	GridlockHoursBypassed string
	CreatedAt             sql.NullTime
}

type Employee struct {
	ID        int32
	Name      string
	Email     string
	EcoPoints int32
	CreatedAt sql.NullTime
}

type FeedbackLoop struct {
	ID               int32
	RouteLogID       sql.NullInt32
	EmployeeID       sql.NullInt32
	RatingScore      int32
	WeatherCondition sql.NullString
	PenaltyApplied   sql.NullBool
	CreatedAt        sql.NullTime
}

type Perk struct {
	ID                int32
	Name              string
	PointCost         int32
	QuantityAvailable int32
	CreatedAt         sql.NullTime
}

type WfhRequest struct {
	ID         int32
	EmployeeID sql.NullInt32
	Date       time.Time
	Reason     string
	Status     sql.NullString
	CreatedAt  sql.NullTime
}

type ZoneOccupancy struct {
	ID               int32
	FloorNumber      int32
	ZoneID           string
	CurrentHeadcount sql.NullInt32
	MaxCapacity      int32
	UpdatedAt        sql.NullTime
}
