// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ClaimedPerk struct {
	ID         int32
	EmployeeID pgtype.Int4
	PerkID     pgtype.Int4
	CreatedAt  pgtype.Timestamptz
}

type EcoRouteLog struct {
	ID                    int32
	EmployeeID            pgtype.Int4
	TransportMode         string
	DistanceKm            pgtype.Numeric
	Co2SavedKg            pgtype.Numeric
	GridlockHoursBypassed pgtype.Numeric
	CreatedAt             pgtype.Timestamptz
}

type Employee struct {
	ID           int32
	Name         string
	Email        string
	EcoPoints    int32
	CreatedAt    pgtype.Timestamptz
	PasswordHash string
	Role         string
}

type FeedbackLoop struct {
	ID               int32
	RouteLogID       pgtype.Int4
	EmployeeID       pgtype.Int4
	RatingScore      int32
	WeatherCondition pgtype.Text
	PenaltyApplied   pgtype.Bool
	CreatedAt        pgtype.Timestamptz
}

type Perk struct {
	ID                int32
	Name              string
	PointCost         int32
	QuantityAvailable int32
	CreatedAt         pgtype.Timestamptz
}

type WfhRequest struct {
	ID         int32
	EmployeeID pgtype.Int4
	Date       pgtype.Date
	Reason     string
	Status     pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type ZoneOccupancy struct {
	ID               int32
	FloorNumber      int32
	ZoneID           string
	CurrentHeadcount pgtype.Int4
	MaxCapacity      int32
	UpdatedAt        pgtype.Timestamptz
}
