// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAvailablePerks = `-- name: GetAvailablePerks :many
SELECT id, name, point_cost, quantity_available, created_at FROM perks WHERE quantity_available > 0
`

func (q *Queries) GetAvailablePerks(ctx context.Context) ([]Perk, error) {
	rows, err := q.db.Query(ctx, getAvailablePerks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Perk
	for rows.Next() {
		var i Perk
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PointCost,
			&i.QuantityAvailable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCorporateCarbonMetrics = `-- name: GetCorporateCarbonMetrics :one
SELECT 
    COALESCE(SUM(co2_saved_kg), 0)::NUMERIC as total_co2_eliminated,
    COALESCE(SUM(gridlock_hours_bypassed), 0)::NUMERIC as total_hours_saved
FROM eco_route_logs
`

type GetCorporateCarbonMetricsRow struct {
	TotalCo2Eliminated pgtype.Numeric
	TotalHoursSaved    pgtype.Numeric
}

func (q *Queries) GetCorporateCarbonMetrics(ctx context.Context) (GetCorporateCarbonMetricsRow, error) {
	row := q.db.QueryRow(ctx, getCorporateCarbonMetrics)
	var i GetCorporateCarbonMetricsRow
	err := row.Scan(&i.TotalCo2Eliminated, &i.TotalHoursSaved)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT id, name, eco_points FROM employees 
ORDER BY eco_points DESC LIMIT 10
`

type GetLeaderboardRow struct {
	ID        int32
	Name      string
	EcoPoints int32
}

func (q *Queries) GetLeaderboard(ctx context.Context) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(&i.ID, &i.Name, &i.EcoPoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role, eco_points 
FROM employees 
WHERE email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	Role         string
	EcoPoints    int32
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EcoPoints,
	)
	return i, err
}

const logEcoRoute = `-- name: LogEcoRoute :one
INSERT INTO eco_route_logs (employee_id, transport_mode, distance_km, co2_saved_kg, gridlock_hours_bypassed)
VALUES ($1, $2, $3, $4, $5) RETURNING id, created_at
`

type LogEcoRouteParams struct {
	EmployeeID            pgtype.Int4
	TransportMode         string
	DistanceKm            pgtype.Numeric
	Co2SavedKg            pgtype.Numeric
	GridlockHoursBypassed pgtype.Numeric
}

type LogEcoRouteRow struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) LogEcoRoute(ctx context.Context, arg LogEcoRouteParams) (LogEcoRouteRow, error) {
	row := q.db.QueryRow(ctx, logEcoRoute,
		arg.EmployeeID,
		arg.TransportMode,
		arg.DistanceKm,
		arg.Co2SavedKg,
		arg.GridlockHoursBypassed,
	)
	var i LogEcoRouteRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const updateEmployeePoints = `-- name: UpdateEmployeePoints :exec
UPDATE employees SET eco_points = eco_points + $1 WHERE id = $2
`

type UpdateEmployeePointsParams struct {
	EcoPoints int32
	ID        int32
}

func (q *Queries) UpdateEmployeePoints(ctx context.Context, arg UpdateEmployeePointsParams) error {
	_, err := q.db.Exec(ctx, updateEmployeePoints, arg.EcoPoints, arg.ID)
	return err
}
